version: v1.0.0

dsn: memory

serve:
  public:
    base_url: https://uni-play.ru/
    host: 127.0.0.1
    cors:
      enabled: true
  admin:
    base_url: http://127.0.0.1:4434/
    host: 127.0.0.1

selfservice:
  default_browser_return_url: https://uni-play.ru/auth/
  allowed_return_urls:
    - https://uni-play.ru

  methods:
    password:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      enabled: true # config loaded from env

  flows:
    error:
      ui_url: https://uni-play.ru/auth/errors

    settings:
      ui_url: https://uni-play.ru/auth/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://uni-play.ru/auth/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://uni-play.ru/auth/verification
      use: code
      after:
        default_browser_return_url: https://uni-play.ru/auth/

    logout:
      after:
        default_browser_return_url: https://uni-play.ru/auth/login

    login:
      ui_url: https://uni-play.ru/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://uni-play.ru/auth/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
        oidc:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 3
    salt_length: 16
    key_length: 32

identity:
  default_schema_id: user
  schemas:
    - id: user
      url: file:///etc/config/kratos/schemas/user.schema.json
    - id: organizer
      url: file:///etc/config/kratos/schemas/organizer.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
