version: "3.9"

volumes:
  pg-data:
  grafana-data:

services:

  postgres:
    image: "postgres:15.3-alpine"
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "14268:14268"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./build/prometheus/dev.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafana-data:/var/lib/grafana
      - ./build/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

  app:
    image: app
    container_name: app
    restart: unless-stopped
    build: .
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
