BEGIN
;

DROP TABLE IF EXISTS player_match_weapon_stat CASCADE;

DROP TABLE IF EXISTS player_match CASCADE;

DROP TABLE IF EXISTS weapon CASCADE;

DROP TABLE IF EXISTS weapon_class CASCADE;

DROP TABLE IF EXISTS player_match_stat CASCADE;

DROP TABLE IF EXISTS match CASCADE;

DROP TABLE IF EXISTS team_player CASCADE;

DROP TABLE IF EXISTS player CASCADE;

DROP TABLE IF EXISTS team CASCADE;

DROP TABLE IF EXISTS university CASCADE;

COMMIT;