DROP TABLE IF EXISTS weapon_metric CASCADE;

DROP TABLE IF EXISTS metric CASCADE;

DROP TABLE IF EXISTS match CASCADE;

DROP TABLE IF EXISTS team_player CASCADE;

DROP TABLE IF EXISTS player CASCADE;

DROP TABLE IF EXISTS team CASCADE;