BEGIN;

DROP TABLE IF EXISTS weapon_metric CASCADE;

DROP TABLE IF EXISTS weapon CASCADE;

DROP TABLE IF EXISTS weapon_class CASCADE;

DROP TABLE IF EXISTS metric CASCADE;

DROP TABLE IF EXISTS match_player CASCADE;

DROP TYPE IF EXISTS match_player_state;

DROP TABLE IF EXISTS match CASCADE;

DROP TABLE IF EXISTS team_player CASCADE;

DROP TABLE IF EXISTS player CASCADE;

DROP TABLE IF EXISTS team CASCADE;

COMMIT;