version: "3.9"

volumes:
  pg-data:
  grafana-data:
  minio-data:
    driver: local

services:

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-02T10-51-33Z
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=secretpassword

  postgres:
    image: "postgres:16.1-alpine"
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    image: app
    container_name: app
    restart: unless-stopped
    build: .
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
