version: '3.7'

networks:
  intranet:

volumes:
  kratos-pg:

services:

  kratos-pg:
    image: postgres:16.1-alpine
    volumes:
      - type: volume
        source: kratos-pg
        target: /var/lib/postgresql/data
        read_only: false
    ports:
      - "5433:5432"
    command: -p 5433
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

  kratos-migrate:
    depends_on:
      - kratos-pg
    image: oryd/kratos:${VERSION:?err}
    env_file:
      - .env
    environment:
      - DSN=postgres://kratos:secret@kratos-pg:5433/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: volume
        source: kratos-pg
        target: /var/lib/postgresql/data
        read_only: false
      - type: bind
        source: ${CONFIG_PATH:?err}
        target: /etc/config/kratos/kratos.yml
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:${VERSION:?err}
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DSN=postgres://kratos:secret@kratos-pg:5433/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-pg
        target: /var/lib/postgresql/data
        read_only: false
      - type: bind
        source: ${CONFIG_PATH:?err}
        target: /etc/config/kratos/kratos.yml
      - type: bind
        source: ./schemas/
        target: /etc/config/kratos/schemas/
      - type: bind
        source: ./oidc
        target: /etc/oidc
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:${VERSION:?err}
    ports:
      - "4455:4455"
    env_file:
      - .env
    environment:
      - PORT=4455
      - SECURITY_MODE=
    networks:
      - intranet
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
