version: '3.7'

networks:
  intranet:

volumes:
  kratos-pg:

services:

  kratos-pg:
    image: postgres:16.1-alpine
    volumes:
      - type: volume
        source: kratos-pg
        target: /var/lib/postgresql/data
        read_only: false
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
      - PGUSER=kratos # for psql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "kratos"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - intranet

  kratos-migrate:
    depends_on:
      - kratos-pg
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://kratos:secret@kratos-pg:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: volume
        source: kratos-pg
        target: /var/lib/postgresql/data
        read_only: false
      - type: bind
        source: ./configs/kratos.dev.yml
        target: /etc/config/kratos/kratos.yml
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DSN=postgres://kratos:secret@kratos-pg:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=debug
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-pg
        target: /var/lib/postgresql/data
        read_only: false
      - type: bind
        source: ./configs/kratos.dev.yml
        target: /etc/config/kratos/kratos.yml
      - type: bind
        source: ./schemas/
        target: /etc/config/kratos/schemas/
      - type: bind
        source: ./oidc
        target: /etc/oidc
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.0.0
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SECURITY_MODE=
      - KRATOS_PUBLIC_URL=https://dev.uni-play.ru/kratos/
    networks:
      - intranet
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
